### ISSUE TITLE
How to connect mobile keplr wallet?

### ISSUE THREAD

**Issue by sheriff-rango** [DA0-DA0/docs#46]
I am building a website working on the Juno chain that connects Keplr wallet.
I have connected the Keplr wallet on the desktop version and want to connect Mobile Keplr Wallet.
I tried it using cosmodal but failed and found that https://daodao.zone/starred works well.
I would be very thankful if you could share the code for connecting Mobile Keplr Wallet.

**Comment by NoahSaso** [comment]
Take a look at https://github.com/NoahSaso/cosmodal

I forked cosmodal and made some changes because it didn't work quite right for me either. You can use it right now via the npm package `@noahsaso/cosmodal`, but I have not put a lot of time into cleaning it up yet! I'll be making some improvements in the coming week or two to improve the API and integrate the CW client so it is more general & useful :)

**Comment by NoahSaso** [comment]
> I am building a website working on the Juno chain that connects Keplr wallet. I have connected the Keplr wallet on the desktop version and want to connect Mobile Keplr Wallet. I tried it using cosmodal but failed and found that https://daodao.zone/starred works well. I would be very thankful if you could share the code for connecting Mobile Keplr Wallet.

Take a look at https://github.com/NoahSaso/cosmodal

I forked cosmodal and made some changes because it didn't work quite right for me either. You can use it right now via the npm package `@noahsaso/cosmodal`, but I have not put a lot of time into cleaning it up yet! I'll be making some improvements in the coming week or two to improve the API and integrate the CW client so it is more general & useful :)

**Comment by sheriff-rango** [comment]
I have got this issue with @noahsaso/cosmodal@0.4.2
![image](https://user-images.githubusercontent.com/95250818/175562161-9921df76-6c7f-4210-a32f-7ad1b7fb57d3.png)

How can I fix this issue?

**Comment by NoahSaso** [comment]
> I have got this issue with @noahsaso/cosmodal@0.4.2 ![image](https://user-images.githubusercontent.com/95250818/175562161-9921df76-6c7f-4210-a32f-7ad1b7fb57d3.png)
> 
> How can I fix this issue?

Please try installing the latest `@noahsaso/cosmodal` v0.5.0 and following the updated instructions in the README at https://github.com/NoahSaso/cosmodal or checking out the example in that repo.

If you still can't get it to work, I can help you out in the DAO DAO Discord :) https://discord.gg/sAaGuyW3D2

**Comment by sheriff-rango** [comment]
Thanks for your help, @NoahSaso.
I would like to know if there is some way to auto-connect when the page refreshes.

**Comment by NoahSaso** [comment]
> Thanks for your help, @NoahSaso.
> 
> I would like to know if there is some way to auto-connect when the page refreshes.

Yep! If you set `localStorageKey` on the provider, it will enable auto-connect.

**Comment by sheriff-rango** [comment]
Great! Awesome.

**Comment by sheriff-rango** [comment]
Can I use `@noahsaso/cosmodal` in Angular13?

**Comment by sheriff-rango** [comment]
Can I use `@noahsaso/cosmodal` in Angular13?
